# Site settings
title: "attack-macOS"
description: "A collection of MITRE ATT&CK for macOS techniques"
baseurl: "/attack-macOS"
url: "https://darmado.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub metadata
github:
  repository_nwo: darmado/attack-macOS

# Navigation
header_pages:
  - README.md
  - docs/ROADMAP.md
  - docs/Acknowledgements.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - attackmacos/
  - .tools/
  - venv/
  - logs/

# Collections
collections:
  techniques:
    output: true
    permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "techniques"
    values:
      layout: "technique"

# Sass
sass:
  sass_dir: _sass
  style: compressed 