procedure_name: xattr
tactic: Defense Evasion
ttp_id: T1553.004
guid: a14a168f-4f8c-4a18-8ffa-87eb17231c4e
intent: Display and manipulate extended attributes. Sourced from LOOBins; confirm
  MITRE mapping for each enabled option.
author: Jason Trost (@jason_trost)
created: '2023-04-20'
updated: '2026-05-03'
version: 1.0.4
platform:
- darwin
detection:
- ioc: Gatekeeper Bypass via Xattr
  analysis: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_xattr_gatekeeper_bypass.yml
- ioc: 'Jamf Protect: Detect activity related to xattr and extended attributes'
  analysis: https://github.com/jamf/jamfprotect/blob/main/custom_analytic_detections/xattr_extended_attributes_activity
resources:
- link: https://www.loobins.io/
  description: "LOOBins \u2014 Living Off The Orchard macOS binaries"
- link: https://attack.mitre.org/techniques/T1553/004/
  description: "MITRE ATT&CK \u2014 T1553.004"
- link: ''
  description: ''
- link: https://megancarney.com/presentations/ExternalReport_ThreatHuntingMacOS.pdf
  description: Threat Hunting the macOS edition Megan Carney (Report)
- link: https://www.youtube.com/watch?v=_K4gnSuDkRM&feature=youtu.be
  description: 'GrrCon 2018: Threat Hunting the macOS edition Megan Carney'
acknowledgement:
- person: ''
  handle: ''
procedure:
  arguments:
  - option: --bypass-gatekeeper-via-xattr
    description: Use xattr to remove quaratine extended attribute from a file.
    execute_function:
    - execute_bypass_gatekeeper_via_xattr
  - option: --bypass-gatekeeper-via-xattr
    description: Use xattr to remove quaratine extended attribute from multiple files
      or directories.
    execute_function:
    - execute_bypass_gatekeeper_via_xattr
  global_variable:
  - name: CMD_XATTR
    type: string
    default_value: /usr/bin/xattr
  functions:
  - name: execute_bypass_gatekeeper_via_xattr
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
        exit_on_failure: true
    code: "execute_bypass_gatekeeper_via_xattr() {\n    local result\n    result=$(xattr\
      \ -d com.apple.quarantine FILE 2>&1)\n    $CMD_PRINTF \"RESULT|%s\\n\" \"$result\"\
      \n    return 0\n}"
  - name: execute_bypass_gatekeeper_via_xattr
    type: main
    language:
    - shell
    opsec:
      check_fda:
        enabled: false
        exit_on_failure: true
    code: "execute_bypass_gatekeeper_via_xattr() {\n    local result\n    result=$(xattr\
      \ -d -r com.apple.quarantine * 2>&1)\n    $CMD_PRINTF \"RESULT|%s\\n\" \"$result\"\
      \n    return 0\n}"
